language: python
python:
  - "3.6"
# command to run tests
install:
    - pip install selenium
    - pip install behave
    - pip install requests
    - pip install bottle
script:
  - cd kent-search-val
  - behave
  - cd ../travis-ci-example
  - python3 test_calc.py
  - cd ../parser-unit-test
  - python3 parser_test.py
 
